name: Build extension

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out repo and set up web-ext for building extension
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --global web-ext

      # Lint and build extension
      - run: web-ext lint
      - run: web-ext build

      # Set name for tag to be released
      - run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
      - run: echo "TAG=$(date +%Y-%m-%d)-$SHORT_SHA" >> "$GITHUB_ENV"

      # Create release on github for extension
      - run: gh release create "$TAG" --title "$TAG" --notes "" ./web-ext-artifacts/*.zip
